# Generated by Django 4.0.4 on 2022-05-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0006_info_delete_relationshipsterms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='RelationshipsTerms',
        ),
    ]
