# Generated by Django 4.0.4 on 2022-05-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0007_rename_info_relationshipsterms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationshipsterms',
            name='title',
        ),
    ]
