# Generated by Django 4.0.4 on 2022-05-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0009_rename_relationshipsterms_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='RT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therm_id', models.IntegerField(verbose_name='первый термин')),
                ('therm_title', models.CharField(max_length=100, verbose_name='второй термин')),
                ('connection', models.CharField(max_length=100, verbose_name='Связь терминов')),
            ],
            options={
                'verbose_name': 'Связь терминов',
                'verbose_name_plural': 'Связи терминов',
            },
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
