# Generated by Django 4.0.4 on 2022-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0013_relationshipstherm_delete_relationships'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mierda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='термин')),
                ('body', models.TextField(verbose_name='Определение')),
            ],
            options={
                'verbose_name': 'определение',
                'verbose_name_plural': 'определения',
            },
        ),
    ]
